/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  '/auth/begin': {
    /**
     * Begins the authentication process
     * @description Begins the authentication process by providing the public address of the user. System will return a random nonce used for signature validation.
     */
    post: operations['authentication.Begin'];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    /** @description The public address of the user. */
    PublicAddress: string;
    /**
     * @example {
     *   "publicAddress": "0xb794f5ea0ba39494ce839613fffba74279579268"
     * }
     */
    AuthBeginRequest: {
      publicAddress: components['schemas']['PublicAddress'];
    };
    /**
     * @example {
     *   "publicAddress": "0xb794f5ea0ba39494ce839613fffba74279579268",
     *   "nonce": "0x1234567890abcdef"
     * }
     */
    AuthBeginResponse: {
      publicAddress: components['schemas']['PublicAddress'];
      /** @description The nonce used for signature validation */
      nonce: string;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {
  /**
   * Begins the authentication process
   * @description Begins the authentication process by providing the public address of the user. System will return a random nonce used for signature validation.
   */
  'authentication.Begin': {
    requestBody?: {
      content: {
        'application/json': components['schemas']['AuthBeginRequest'];
      };
    };
    responses: {
      /** @description OK */
      200: {
        content: {
          'application/json': components['schemas']['AuthBeginResponse'];
        };
      };
    };
  };
}
