services:
  db:
    image: postgres:latest
    restart: always
    healthcheck:
      test: ['CMD', 'pg_isready', '-q', '-d', 'sesame', '-U', 'sesame']
      timeout: 5s
      interval: 10s
      retries: 5
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - '5432:5432'
    volumes:
      - ./.docker/db:/var/lib/postgresql/data
  redis:
    image: redis:latest
    restart: always
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
    ports:
      - '6379:6379'
    environment:
      REDIS_PASSWORD: panther
      ALLOW_EMPTY_PASSWORD: no
