version: 2.1

orbs:
  docker: circleci/docker@2.4.0

commands:
  install-bun:
    steps:
      - run:
          name: 'Install bun'
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> "$BASH_ENV"
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            bun --version

  install-git:
    steps:
      - run:
          name: 'Install git'
          command: |
            apt-get update
            apt-get install -y git
            apt-get clean
            rm -rf /var/lib/apt/lists/*

jobs:
  lint:
    docker:
      - image: cimg/node:current
      # - image: oven/bun:latest
    steps:
      - checkout

      # Installing bun on a node image for now because official oven/bun image does not have git in it
      # which causes husky prepare to fail.
      - install-bun

      # Installing git on a bun image because husky needs it
      # https://github.com/oven-sh/bun/issues/4687
      # - install-git

      - run:
          name: Restore packages
          command: bun install

      - run:
          name: Check formatting
          command: bun run format

      - run:
          name: Check linting
          command: bun run lint

  build-and-test:
    docker:
      - image: cimg/node:current
      # - image: oven/bun:latest
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - docker/install-dockerize
      - checkout

      # Installing bun on a node image for now because official oven/bun image does not have git in it
      # which causes husky prepare to fail.
      - install-bun

      # Installing git on a bun image because husky needs it
      # https://github.com/oven-sh/bun/issues/4687
      # - install-git

      - run:
          name: Restore packages
          command: bun install

      - run:
          name: Create env vars
          command: bun run env

      - run:
          name: Wait for postgres to be ready
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      - run:
          name: Migrate database
          command: bun x prisma migrate dev

      - run:
          name: Run tests
          command: bun run test

workflows:
  main:
    jobs:
      - lint
      - build-and-test:
          requires:
            - lint
