version: 2.1

orbs:
  docker: circleci/docker@2.2.0

commands:
  install-bun:
    steps:
      - run:
          name: 'Install bun'
          command: |
            curl -fsSL https://bun.sh/install | bash
            echo 'export BUN_INSTALL="$HOME/.bun"' >> "$BASH_ENV"
            echo 'export PATH="$BUN_INSTALL/bin:$PATH"' >> "$BASH_ENV"
            source "$BASH_ENV"
            bun --version

jobs:
  lint:
    docker:
      - image: cimg/node:current
      # - image: oven/bun:latest
    steps:
      - checkout

      # Installing bun on a node image for now because official oven/bun image does not have git in it
      # which causes husky prepare to fail.
      - install-bun

      - run:
          name: Restore packages
          command: bun install

      - run:
          name: Check formatting
          command: bun run format

      - run:
          name: Check linting
          command: bun run lint

  build-and-test:
    docker:
      - image: cimg/node:current
      - image: postgres:latest
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
    steps:
      - docker/install-dockerize
      - install-bun
      - checkout

      - run:
          name: Restore packages
          command: bun install

      - run:
          name: Run tests
          command: bun run test

workflows:
  main:
    jobs:
      - lint
      - build-and-test:
          requires:
            - lint
